# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 381)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 20, 231, 51))
        self.label.setObjectName("label")
        self.signature_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.signature_txt.setGeometry(QtCore.QRect(140, 190, 401, 87))
        self.signature_txt.setObjectName("signature_txt")
        self.Verify_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Verify_btn.setGeometry(QtCore.QRect(420, 290, 93, 28))
        self.Verify_btn.setObjectName("Verify_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 111, 31))
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(0)
        self.label_3.setObjectName("label_3")
        self.sign_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sign_btn.setGeometry(QtCore.QRect(180, 290, 93, 28))
        self.sign_btn.setObjectName("sign_btn")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 111, 21))
        self.label_5.setObjectName("label_5")
        self.information_txt = QtWidgets.QTextEdit(self.centralwidget)
        self.information_txt.setGeometry(QtCore.QRect(140, 80, 401, 87))
        self.information_txt.setObjectName("information_txt")
        self.generateKeys_btn = QtWidgets.QPushButton(self.centralwidget)
        self.generateKeys_btn.setGeometry(QtCore.QRect(330, 30, 93, 28))
        self.generateKeys_btn.setObjectName("generateKeys_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 588, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ECC CIPHER - ecc.ui"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">ECC Cipher</span></p></body></html>"))
        self.Verify_btn.setText(_translate("MainWindow", "Verify"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Information:</span></p></body></html>"))
        self.sign_btn.setText(_translate("MainWindow", "Sign"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic;\">Signature:</span></p></body></html>"))
        self.generateKeys_btn.setText(_translate("MainWindow", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
